name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Git identity
        run: |
          git config --global user.name "xms312"
          git config --global user.email "2938754867@qq.com"

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run docs:build

      - name: Debug dist output
        run: ls -la ./docs/.vitepress/dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vitepress/dist
          force_orphan: true
